#!/usr/bin/env bash

clear

if [ "$1" == "build" ]; then 

	# First, setup Oasis
	oasis setup || exit

	# Then, clean up
	make clean distclean || exit
	clear

	# Afterwards, add stuff to the files
	if grep -q 'mark_tag_used("tests")' myocamlbuild.ml; then
		: # Do nothing
	else
		echo "" >> myocamlbuild.ml
		echo 'mark_tag_used("tests")' >> myocamlbuild.ml
	fi

	if grep -q '# _TAGS ADDED' _tags; then
		: # Again, do nothing
	else
		echo "" >> _tags; echo "" >> _tags
		echo "# _TAGS ADDED" >> _tags

		# Disable -41 for Menhir
		echo "<src/CrabParsing/parser.*>: warn(+A-4-6-9-40..42-44), warn_error(+1..49), strict_sequence, safe_string" >> _tags
		# Otherwise, keep our defined default
		echo "<src/**.ml{,i}>: warn(+A-4-6-9-40-42-44), warn_error(+1..49), strict_sequence, safe_string" >> _tags
		echo '' >> _tags
	fi

	./configure || exit

	# Finally, build
	make build || exit

	clear

	mv crab.native crab || exit

	if [ "$2" == "run" ]; then
		if [ -f crab ]; then
			./crab $3 || exit
		else
			echo "

			Please build by running 'run build'"
		fi
	elif [ "$2" == "tests" ]; then
		./configure --enable-tests
		clear
		make test || exit
	else 
		if [ -f crab ]; then
			./crab $2 || exit
		else
			echo "

			Please build by running 'run build'"
		fi
	fi

elif [ "$1" == "run" ]; then
	if [ "$2" == "tests" ]; then
		make test || echo "

		Please build by running 'run build tests'"
	else
		if [ -f crab ]; then
			./crab $2 || exit
		else
			echo "

			Please build by running 'run build'"
		fi
	fi
elif [ "$1" == "tests" ]; then
	make test || echo "

		Please build by running 'run build tests'"
else
	if [ -f crab ]; then
			./crab $1 || exit
		else
			echo "

			Please build by running 'run build'"
		fi
fi