#!/usr/bin/env bash

clear

if [ "$1" == "build" ]; then 

	# First, clean up
	make clean distclean || exit
	clear

	# Then, setup Oasis
	oasis setup || exit

	# Afterwards, add stuff to the files
	if grep -q 'mark_tag_used("tests")' myocamlbuild.ml; then
		: # Again, do nothing
	else
		echo "" >> myocamlbuild.ml
		echo 'mark_tag_used("tests")' >> myocamlbuild.ml
	fi

	./configure || exit

	# Finally, build
	make build || exit

	clear

	mv crab.native crab || exit

	if [ "$2" == "run" ]; then
		if [ -f crab ]; then
			./crab $3 || exit
		else
			echo "

			Please build by running 'run build'"
		fi 
	else 
		if [ -f crab ]; then
			./crab $2 || exit
		else
			echo "

			Please build by running 'run build'"
		fi
	fi

elif [ "$1" == "tests" ]; then
	make clean distclean || exit
	./configure --enable-tests || exit
	clear
	make test || exit

elif [ "$1" == "run" ]; then
	if [ "$2" == "test" ]; then
		make test || echo "

		Please build by running 'run build'"
	else
		if [ -f crab ]; then
			./crab $2 || exit
		else
			echo "

			Please build by running 'run build'"
		fi
	fi
else
	if [ -f crab ]; then
			./crab $1 || exit
		else
			echo "

			Please build by running 'run build'"
		fi
fi